import $ from "jquery";
import {navbar_toggle, accordion_click} from "./home";
import {form_validation} from "./form-validation";
import {comp_form} from "./comps-form";
import {youtubeApi} from "./you-tube-api";

import "../styles/_fonts.scss";
import "../styles/_variables.scss";
import "../styles/_mixins.scss";
import "../styles/_normalise.scss";
import "../styles/_flexbox.scss";
import "../styles/_common.scss";
import "../styles/_nav.scss";
import "../styles/_header.scss";
import "../styles/_tiles.scss";
import "../styles/_comp.scss";
import "../styles/_comps-form.scss";
import "../styles/_manifesto.scss";
import "../styles/_explore.scss";
import "../styles/_testimonial.scss";
import "../styles/_quote.scss";
import "../styles/_faqs.scss";
import "../styles/_bottom-nav.scss";
import "../styles/_footer.scss";
import "../styles/_footer-social.scss";
import "../styles/_accordion.scss";
// import "../styles/_modal-video.scss";
import "../styles/_youtube-popup.scss";