import {navbar_toggle, accordion_click, navbar_click, what_os} from "./home"; 
import {journey} from "./journey/journey";
import {form_validation} from "./form-validation";
import {modifySelect, fancy_scrollbar} from "./select2";
import {reg_form_validation} from "./journey/register";


import "../styles/_fonts.scss";
import "../styles/_variables.scss";
import "../styles/_mixins.scss";
import "../styles/_normalise.scss";
import "../styles/_flexbox.scss";
import "../styles/_common.scss";
import "../styles/_nav.scss";
import "../styles/_header.scss";
import "../styles/_tiles.scss";
import "../styles/_comp.scss";
import "../styles/_comps-form.scss";
import "../styles/_manifesto.scss";
import "../styles/_explore.scss";
import "../styles/_testimonial.scss";
import "../styles/_quote.scss";
import "../styles/_faqs.scss";
import "../styles/_bottom-nav.scss";
import "../styles/_footer.scss";
import "../styles/_footer-social.scss";
import "../styles/_accordion.scss";
import "../styles/_youtube-popup.scss";
import "../styles/_journey.scss";
import "../styles/_modal.scss";
import "../styles/_select.scss";
import "../styles/_select2.scss";
import "../styles/_scrollbar.scss";
import "../styles/_buttons.scss";